name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Jalankan workflow saat ada push ke branch 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js 18
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/dicoding-mlgc-submission:latest .

      # Push Docker image to Google Container Registry
      - name: Push Docker image to GCR
        run: |
          echo ${{ secrets.GCP_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker
          docker push gcr.io/$GCP_PROJECT_ID/dicoding-mlgc-submission:latest

      # Deploy Docker image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dicoding-mlgc-submission \
            --image gcr.io/$GCP_PROJECT_ID/dicoding-mlgc-submission:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080
