name: Build, Push, and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        version: '395.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/submission-mlgc:latest .

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/submission-mlgc:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        version: '395.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy submission-mlgc \
          --image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/submission-mlgc:latest \
          --region=asia-southeast2 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \
          --set-env-vars MODEL_URL=${{ secrets.MODEL_URL }} \
          --set-env-vars STORAGE_KEY_PATH=/workspace/storage_key.json \
          --port=8080  # Pastikan aplikasi mendengarkan pada port 8080
          
    - name: Set up Cloud Run IAM Policy
      run: |
        gcloud run services add-iam-policy-binding submission-mlgc \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=asia-southeast2
